// Pesos moleculares de reactivos comunes (g/mol), para no tener que buscarlos. Las sales
// hidratadas cambian de peso: verifica la forma exacta en la etiqueta del frasco. El usuario
// puede guardar los suyos en su biblioteca de reactivos.
export const COMMON_REAGENTS: { name: string; formula: string; mw: number }[] = [
  { name: "Cloruro de sodio", formula: "NaCl", mw: 58.44 },
  { name: "Cloruro de potasio", formula: "KCl", mw: 74.55 },
  { name: "Fosfato disódico anhidro", formula: "Na2HPO4", mw: 141.96 },
  { name: "Fosfato disódico heptahidratado", formula: "Na2HPO4·7H2O", mw: 268.07 },
  { name: "Fosfato disódico dodecahidratado", formula: "Na2HPO4·12H2O", mw: 358.14 },
  { name: "Fosfato monopotásico", formula: "KH2PO4", mw: 136.09 },
  { name: "Fosfato monosódico monohidratado", formula: "NaH2PO4·H2O", mw: 137.99 },
  { name: "Fosfato monosódico dihidratado", formula: "NaH2PO4·2H2O", mw: 156.01 },
  { name: "Tris base", formula: "C4H11NO3", mw: 121.14 },
  { name: "Tris-HCl", formula: "C4H11NO3·HCl", mw: 157.6 },
  { name: "EDTA disódico dihidratado", formula: "Na2EDTA·2H2O", mw: 372.24 },
  { name: "HEPES", formula: "C8H18N2O4S", mw: 238.3 },
  { name: "Glicina", formula: "C2H5NO2", mw: 75.07 },
  { name: "SDS (dodecilsulfato de sodio)", formula: "NaC12H25SO4", mw: 288.38 },
  { name: "Sacarosa", formula: "C12H22O11", mw: 342.3 },
  { name: "D-glucosa", formula: "C6H12O6", mw: 180.16 },
  { name: "Glicerol", formula: "C3H8O3", mw: 92.09 },
  { name: "Cloruro de magnesio hexahidratado", formula: "MgCl2·6H2O", mw: 203.3 },
  { name: "Cloruro de calcio dihidratado", formula: "CaCl2·2H2O", mw: 147.01 },
  { name: "Bicarbonato de sodio", formula: "NaHCO3", mw: 84.01 },
  { name: "Cloruro de amonio", formula: "NH4Cl", mw: 53.49 },
  { name: "Hidróxido de sodio", formula: "NaOH", mw: 40.0 },
  { name: "Ácido clorhídrico", formula: "HCl", mw: 36.46 },
  { name: "Citrato trisódico dihidratado", formula: "Na3C6H5O7·2H2O", mw: 294.1 },
  { name: "Ácido cítrico monohidratado", formula: "C6H8O7·H2O", mw: 210.14 },
  { name: "Tetraborato de sodio decahidratado (bórax)", formula: "Na2B4O7·10H2O", mw: 381.37 },
  { name: "Imidazol", formula: "C3H4N2", mw: 68.08 },
  { name: "DTT (ditiotreitol)", formula: "C4H10O2S2", mw: 154.25 },
  { name: "β-mercaptoetanol", formula: "C2H6OS", mw: 78.13 },
  { name: "Persulfato de amonio (APS)", formula: "(NH4)2S2O8", mw: 228.2 },
  { name: "Azida de sodio", formula: "NaN3", mw: 65.01 },
  { name: "Etanol", formula: "C2H5OH", mw: 46.07 },
  { name: "Peróxido de hidrógeno", formula: "H2O2", mw: 34.01 },
  { name: "Paraformaldehído (como formaldehído)", formula: "(CH2O)n", mw: 30.03 },
  { name: "Glutaraldehído", formula: "C5H8O2", mw: 100.12 },
  { name: "Cacodilato de sodio trihidratado", formula: "Na(CH3)2AsO2·3H2O", mw: 214.03 },
  { name: "Tetróxido de osmio", formula: "OsO4", mw: 254.23 },
  { name: "Acetato de uranilo dihidratado", formula: "UO2(CH3COO)2·2H2O", mw: 424.15 },
  { name: "DAB tetraclorhidrato", formula: "C12H14N4·4HCl", mw: 360.1 },
  { name: "Azul de toluidina O", formula: "C15H16ClN3S", mw: 305.83 },
];
